//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITE_COMPLEMENTAIRE
    {
        public ACTIVITE_COMPLEMENTAIRE()
        {
            this.PARTICIPE = new HashSet<PARTICIPE>();
            this.COLLABORATEUR1 = new HashSet<COLLABORATEUR>();
        }
    
        public int num_act { get; set; }
        public string theme_act { get; set; }
        public string montant_frais { get; set; }
        public System.DateTime date_act { get; set; }
        public string lieu_act { get; set; }
        public int matricule_col { get; set; }
    
        public virtual COLLABORATEUR COLLABORATEUR { get; set; }
        public virtual ICollection<PARTICIPE> PARTICIPE { get; set; }
        public virtual ICollection<COLLABORATEUR> COLLABORATEUR1 { get; set; }
    }
}
