//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPOSANT
    {
        public COMPOSANT()
        {
            this.CONSTITUER = new HashSet<CONSTITUER>();
        }
    
        public int code_comp { get; set; }
        public string libelle_comp { get; set; }
    
        public virtual ICollection<CONSTITUER> CONSTITUER { get; set; }
    }
}
