//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSTITUER
    {
        public string quantite_comp { get; set; }
        public string depot_legal { get; set; }
        public int code_comp { get; set; }
    
        public virtual COMPOSANT COMPOSANT { get; set; }
        public virtual MEDICAMENT MEDICAMENT { get; set; }
    }
}
