//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATE
    {
        public DATE()
        {
            this.REMPLACE = new HashSet<REMPLACE>();
        }
    
        public System.DateTime JJMMAAAA { get; set; }
    
        public virtual ICollection<REMPLACE> REMPLACE { get; set; }
    }
}
