//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTEMENT
    {
        public DEPARTEMENT()
        {
            this.COMMUNE = new HashSet<COMMUNE>();
        }
    
        public string code_dep { get; set; }
        public string libelle_dep { get; set; }
        public string code_region { get; set; }
    
        public virtual ICollection<COMMUNE> COMMUNE { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
