//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHE_FRAIS
    {
        public FICHE_FRAIS()
        {
            this.INCLURE = new HashSet<INCLURE>();
        }
    
        public string ff_mois { get; set; }
        public string ff_NBHorsClassif { get; set; }
        public string ff_MontantHorsClassif { get; set; }
        public int matricule_col { get; set; }
    
        public virtual COLLABORATEUR COLLABORATEUR { get; set; }
        public virtual ICollection<INCLURE> INCLURE { get; set; }
    }
}
