//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENT
    {
        public MEDICAMENT()
        {
            this.AVOIR = new HashSet<AVOIR>();
            this.CONSTITUER = new HashSet<CONSTITUER>();
            this.OFFRE = new HashSet<OFFRE>();
            this.PRESCRIRE = new HashSet<PRESCRIRE>();
            this.MEDICAMENT1 = new HashSet<MEDICAMENT>();
            this.MEDICAMENT2 = new HashSet<MEDICAMENT>();
            this.RAPPORT_DE_VISITE = new HashSet<RAPPORT_DE_VISITE>();
        }
    
        public string depot_legal { get; set; }
        public string composition { get; set; }
        public string effet { get; set; }
        public string contreindic { get; set; }
        public double prixechantillon { get; set; }
        public int code_present { get; set; }
        public Nullable<int> code_famille { get; set; }
    
        public virtual ICollection<AVOIR> AVOIR { get; set; }
        public virtual ICollection<CONSTITUER> CONSTITUER { get; set; }
        public virtual FAMILLE FAMILLE { get; set; }
        public virtual PRESENTATION PRESENTATION { get; set; }
        public virtual ICollection<OFFRE> OFFRE { get; set; }
        public virtual ICollection<PRESCRIRE> PRESCRIRE { get; set; }
        public virtual ICollection<MEDICAMENT> MEDICAMENT1 { get; set; }
        public virtual ICollection<MEDICAMENT> MEDICAMENT2 { get; set; }
        public virtual ICollection<RAPPORT_DE_VISITE> RAPPORT_DE_VISITE { get; set; }
    }
}
