//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIF
    {
        public MOTIF()
        {
            this.RAPPORT_DE_VISITE = new HashSet<RAPPORT_DE_VISITE>();
        }
    
        public int code_motif { get; set; }
        public string libelle_motif { get; set; }
    
        public virtual ICollection<RAPPORT_DE_VISITE> RAPPORT_DE_VISITE { get; set; }
    }
}
