//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPE
    {
        public bool speciliteon { get; set; }
        public int matricule_praticien { get; set; }
        public int num_act { get; set; }
    
        public virtual ACTIVITE_COMPLEMENTAIRE ACTIVITE_COMPLEMENTAIRE { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
    }
}
