//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSSEDER
    {
        public string diplome_praticien { get; set; }
        public float coefprescription_praticien { get; set; }
        public int matricule_praticien { get; set; }
        public int code_spec { get; set; }
    
        public virtual SPECIALITE SPECIALITE { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
    }
}
