//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRATICIEN
    {
        public PRATICIEN()
        {
            this.PARTICIPE = new HashSet<PARTICIPE>();
            this.POSSEDER = new HashSet<POSSEDER>();
            this.RAPPORT_DE_VISITE = new HashSet<RAPPORT_DE_VISITE>();
            this.REMPLACE = new HashSet<REMPLACE>();
            this.REMPLACE1 = new HashSet<REMPLACE>();
        }
    
        public int matricule_praticien { get; set; }
        public string nom_praticien { get; set; }
        public string prenom_praticien { get; set; }
        public string adresse_praticien { get; set; }
        public string cp_praticien { get; set; }
        public string ville_praticien { get; set; }
        public float coefnotoriete_praticien { get; set; }
        public bool titulaire_praticien { get; set; }
        public int code_type { get; set; }
        public string numTel { get; set; }
    
        public virtual ICollection<PARTICIPE> PARTICIPE { get; set; }
        public virtual ICollection<POSSEDER> POSSEDER { get; set; }
        public virtual TYPE_PRATICIEN TYPE_PRATICIEN { get; set; }
        public virtual ICollection<RAPPORT_DE_VISITE> RAPPORT_DE_VISITE { get; set; }
        public virtual ICollection<REMPLACE> REMPLACE { get; set; }
        public virtual ICollection<REMPLACE> REMPLACE1 { get; set; }
    }
}
