//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class praticienAdresse
    {
        public int num { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string numTel { get; set; }
        public string adresse { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
    }
}
