//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPPORT_DE_VISITE
    {
        public RAPPORT_DE_VISITE()
        {
            this.OFFRE = new HashSet<OFFRE>();
            this.MEDICAMENT = new HashSet<MEDICAMENT>();
        }
    
        public int num_rapport { get; set; }
        public System.DateTime date_rapport { get; set; }
        public System.DateTime date_visite { get; set; }
        public string bilan_visite { get; set; }
        public int matricule_praticien { get; set; }
        public int matricule_col { get; set; }
        public Nullable<int> code_motif { get; set; }
    
        public virtual COLLABORATEUR COLLABORATEUR { get; set; }
        public virtual MOTIF MOTIF { get; set; }
        public virtual ICollection<OFFRE> OFFRE { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
        public virtual ICollection<MEDICAMENT> MEDICAMENT { get; set; }
    }
}
