//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.DEPARTEMENT = new HashSet<DEPARTEMENT>();
            this.GERE = new HashSet<GERE>();
            this.COLLABORATEUR = new HashSet<COLLABORATEUR>();
        }
    
        public string code_region { get; set; }
        public string nom_region { get; set; }
        public string code_secteur { get; set; }
    
        public virtual ICollection<DEPARTEMENT> DEPARTEMENT { get; set; }
        public virtual ICollection<GERE> GERE { get; set; }
        public virtual SECTEUR SECTEUR { get; set; }
        public virtual ICollection<COLLABORATEUR> COLLABORATEUR { get; set; }
    }
}
