//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMPLACE
    {
        public int matricule_praticien_remplace { get; set; }
        public int matricule_praticien_remplacant { get; set; }
        public System.DateTime JJMMAAAA { get; set; }
    
        public virtual DATE DATE { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
        public virtual PRATICIEN PRATICIEN1 { get; set; }
    }
}
