//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALITE
    {
        public SPECIALITE()
        {
            this.POSSEDER = new HashSet<POSSEDER>();
        }
    
        public int code_spec { get; set; }
        public string libelle_spec { get; set; }
    
        public virtual ICollection<POSSEDER> POSSEDER { get; set; }
    }
}
