//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_PRATICIEN
    {
        public TYPE_PRATICIEN()
        {
            this.PRATICIEN = new HashSet<PRATICIEN>();
        }
    
        public int code_type { get; set; }
        public string type_lieu { get; set; }
        public string libelle_type { get; set; }
    
        public virtual ICollection<PRATICIEN> PRATICIEN { get; set; }
    }
}
