//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_FRAIS
    {
        public TYPE_FRAIS()
        {
            this.INCLURE = new HashSet<INCLURE>();
        }
    
        public string tf_Code { get; set; }
        public string tf_libelle { get; set; }
        public string tf_forfait { get; set; }
    
        public virtual ICollection<INCLURE> INCLURE { get; set; }
    }
}
